# Site settings
title: Patrick Schwab
email: patrick.schwab@hest.ethz.ch
description: > # this means to ignore newlines until "baseurl:"
  Patrick Schwab is a doctoral researcher at ETH Zurich working on machine learning in healthcare.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://schwabpatrick.com/" # the base hostname & protocol for your site
twitter_username: schwabpa
github_username:  d909b
google_scholar_user: MG2IF00AAAAJ
linkedin_username: patrick-schwab

# Build settings
markdown: kramdown
